# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\LiomW17\Desktop\LiclipseWorkspace\daqcode\liomacq_gui\galvos_form.ui'
#
# Created: Tue Oct 16 16:56:36 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GalvosForm(object):
    def setupUi(self, GalvosForm):
        GalvosForm.setObjectName(_fromUtf8("GalvosForm"))
        GalvosForm.resize(749, 536)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GalvosForm.sizePolicy().hasHeightForWidth())
        GalvosForm.setSizePolicy(sizePolicy)
        self.layoutWidget = QtGui.QWidget(GalvosForm)
        self.layoutWidget.setGeometry(QtCore.QRect(357, 10, 387, 486))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_LaserOn = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_LaserOn.setObjectName(_fromUtf8("pushButton_LaserOn"))
        self.gridLayout_3.addWidget(self.pushButton_LaserOn, 9, 0, 1, 3)
        self.lineEdit_laser_output = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_laser_output.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_laser_output.setCursorPosition(3)
        self.lineEdit_laser_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_output.setObjectName(_fromUtf8("lineEdit_laser_output"))
        self.gridLayout_3.addWidget(self.lineEdit_laser_output, 10, 3, 1, 1)
        self.pushButton_CARS_switch = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_CARS_switch.setObjectName(_fromUtf8("pushButton_CARS_switch"))
        self.gridLayout_3.addWidget(self.pushButton_CARS_switch, 11, 0, 1, 4)
        self.pushButton_Shutter_Main = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Shutter_Main.setObjectName(_fromUtf8("pushButton_Shutter_Main"))
        self.gridLayout_3.addWidget(self.pushButton_Shutter_Main, 13, 0, 1, 3)
        self.pushButton_LaserOff = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_LaserOff.setObjectName(_fromUtf8("pushButton_LaserOff"))
        self.gridLayout_3.addWidget(self.pushButton_LaserOff, 9, 3, 1, 1)
        self.pushButton_APT_Motor = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_APT_Motor.setObjectName(_fromUtf8("pushButton_APT_Motor"))
        self.gridLayout_3.addWidget(self.pushButton_APT_Motor, 4, 0, 1, 4)
        self.pushButton_firstcut = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_firstcut.setObjectName(_fromUtf8("pushButton_firstcut"))
        self.gridLayout_3.addWidget(self.pushButton_firstcut, 1, 0, 1, 4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_ZaberY_left = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ZaberY_left.sizePolicy().hasHeightForWidth())
        self.pushButton_ZaberY_left.setSizePolicy(sizePolicy)
        self.pushButton_ZaberY_left.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_ZaberY_left.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/arrow_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZaberY_left.setIcon(icon)
        self.pushButton_ZaberY_left.setObjectName(_fromUtf8("pushButton_ZaberY_left"))
        self.gridLayout.addWidget(self.pushButton_ZaberY_left, 0, 3, 1, 1)
        self.pushButton_ZaberX_right = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ZaberX_right.sizePolicy().hasHeightForWidth())
        self.pushButton_ZaberX_right.setSizePolicy(sizePolicy)
        self.pushButton_ZaberX_right.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_ZaberX_right.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/arrow_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZaberX_right.setIcon(icon1)
        self.pushButton_ZaberX_right.setObjectName(_fromUtf8("pushButton_ZaberX_right"))
        self.gridLayout.addWidget(self.pushButton_ZaberX_right, 1, 4, 1, 1)
        self.pushButton_ZaberX_left = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ZaberX_left.sizePolicy().hasHeightForWidth())
        self.pushButton_ZaberX_left.setSizePolicy(sizePolicy)
        self.pushButton_ZaberX_left.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_ZaberX_left.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/arrow_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZaberX_left.setIcon(icon2)
        self.pushButton_ZaberX_left.setObjectName(_fromUtf8("pushButton_ZaberX_left"))
        self.gridLayout.addWidget(self.pushButton_ZaberX_left, 1, 1, 1, 1)
        self.pushButton_ZaberY_right = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ZaberY_right.sizePolicy().hasHeightForWidth())
        self.pushButton_ZaberY_right.setSizePolicy(sizePolicy)
        self.pushButton_ZaberY_right.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_ZaberY_right.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/arrow_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZaberY_right.setIcon(icon3)
        self.pushButton_ZaberY_right.setObjectName(_fromUtf8("pushButton_ZaberY_right"))
        self.gridLayout.addWidget(self.pushButton_ZaberY_right, 2, 3, 1, 1)
        self.lineEdit_Zaber_step = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Zaber_step.sizePolicy().hasHeightForWidth())
        self.lineEdit_Zaber_step.setSizePolicy(sizePolicy)
        self.lineEdit_Zaber_step.setObjectName(_fromUtf8("lineEdit_Zaber_step"))
        self.gridLayout.addWidget(self.lineEdit_Zaber_step, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_init = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_init.sizePolicy().hasHeightForWidth())
        self.pushButton_init.setSizePolicy(sizePolicy)
        self.pushButton_init.setMaximumSize(QtCore.QSize(48, 48))
        self.pushButton_init.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_init.setObjectName(_fromUtf8("pushButton_init"))
        self.gridLayout.addWidget(self.pushButton_init, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_Settopleft = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Settopleft.setObjectName(_fromUtf8("pushButton_Settopleft"))
        self.horizontalLayout_2.addWidget(self.pushButton_Settopleft)
        self.pushButton_Setbottomright = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Setbottomright.setObjectName(_fromUtf8("pushButton_Setbottomright"))
        self.horizontalLayout_2.addWidget(self.pushButton_Setbottomright)
        self.pushButton_mozaic = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_mozaic.setObjectName(_fromUtf8("pushButton_mozaic"))
        self.horizontalLayout_2.addWidget(self.pushButton_mozaic)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 4)
        self.lineEdit_APT_Motors = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_APT_Motors.setObjectName(_fromUtf8("lineEdit_APT_Motors"))
        self.gridLayout_3.addWidget(self.lineEdit_APT_Motors, 2, 3, 1, 1)
        self.pushButton_getPosthorlabs = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_getPosthorlabs.setObjectName(_fromUtf8("pushButton_getPosthorlabs"))
        self.gridLayout_3.addWidget(self.pushButton_getPosthorlabs, 5, 0, 1, 4)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setEnabled(True)
        self.label_16.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 10, 0, 1, 3)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.pushButton_Shutter_1040 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Shutter_1040.setObjectName(_fromUtf8("pushButton_Shutter_1040"))
        self.gridLayout_3.addWidget(self.pushButton_Shutter_1040, 13, 3, 1, 1)
        self.pushButton_read_power = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_read_power.setObjectName(_fromUtf8("pushButton_read_power"))
        self.gridLayout_3.addWidget(self.pushButton_read_power, 14, 0, 1, 3)
        self.pushButton_move_laser_motor = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_move_laser_motor.setObjectName(_fromUtf8("pushButton_move_laser_motor"))
        self.gridLayout_3.addWidget(self.pushButton_move_laser_motor, 14, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(GalvosForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 341, 528))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setMinimumSize(QtCore.QSize(16, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 3, 1, 1)
        self.pushButton_motor_down = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_motor_down.sizePolicy().hasHeightForWidth())
        self.pushButton_motor_down.setSizePolicy(sizePolicy)
        self.pushButton_motor_down.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_motor_down.setText(_fromUtf8(""))
        self.pushButton_motor_down.setIcon(icon3)
        self.pushButton_motor_down.setObjectName(_fromUtf8("pushButton_motor_down"))
        self.gridLayout_2.addWidget(self.pushButton_motor_down, 2, 5, 1, 1)
        self.pushButton_motor_up = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_motor_up.sizePolicy().hasHeightForWidth())
        self.pushButton_motor_up.setSizePolicy(sizePolicy)
        self.pushButton_motor_up.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_motor_up.setText(_fromUtf8(""))
        self.pushButton_motor_up.setIcon(icon)
        self.pushButton_motor_up.setObjectName(_fromUtf8("pushButton_motor_up"))
        self.gridLayout_2.addWidget(self.pushButton_motor_up, 0, 5, 1, 1)
        self.pushButton_right = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.pushButton_right.sizePolicy().hasHeightForWidth())
        self.pushButton_right.setSizePolicy(sizePolicy)
        self.pushButton_right.setText(_fromUtf8(""))
        self.pushButton_right.setIcon(icon1)
        self.pushButton_right.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_right.setObjectName(_fromUtf8("pushButton_right"))
        self.gridLayout_2.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_up = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up.sizePolicy().hasHeightForWidth())
        self.pushButton_up.setSizePolicy(sizePolicy)
        self.pushButton_up.setText(_fromUtf8(""))
        self.pushButton_up.setIcon(icon)
        self.pushButton_up.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_up.setObjectName(_fromUtf8("pushButton_up"))
        self.gridLayout_2.addWidget(self.pushButton_up, 0, 1, 1, 1)
        self.pushButton_left = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.pushButton_left.sizePolicy().hasHeightForWidth())
        self.pushButton_left.setSizePolicy(sizePolicy)
        self.pushButton_left.setText(_fromUtf8(""))
        self.pushButton_left.setIcon(icon2)
        self.pushButton_left.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_left.setObjectName(_fromUtf8("pushButton_left"))
        self.gridLayout_2.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_center = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.pushButton_center.sizePolicy().hasHeightForWidth())
        self.pushButton_center.setSizePolicy(sizePolicy)
        self.pushButton_center.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/home_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_center.setIcon(icon4)
        self.pushButton_center.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_center.setObjectName(_fromUtf8("pushButton_center"))
        self.gridLayout_2.addWidget(self.pushButton_center, 1, 1, 1, 1)
        self.pushButton_down = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.pushButton_down.sizePolicy().hasHeightForWidth())
        self.pushButton_down.setSizePolicy(sizePolicy)
        self.pushButton_down.setText(_fromUtf8(""))
        self.pushButton_down.setIcon(icon3)
        self.pushButton_down.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_down.setObjectName(_fromUtf8("pushButton_down"))
        self.gridLayout_2.addWidget(self.pushButton_down, 2, 1, 1, 1)
        self.lineEdit_z_motor_step = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_z_motor_step.setObjectName(_fromUtf8("lineEdit_z_motor_step"))
        self.gridLayout_2.addWidget(self.lineEdit_z_motor_step, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_nx = QtGui.QLabel(self.layoutWidget1)
        self.label_nx.setObjectName(_fromUtf8("label_nx"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_nx)
        self.lineEdit_nx = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_nx.setObjectName(_fromUtf8("lineEdit_nx"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_nx)
        self.label_ny = QtGui.QLabel(self.layoutWidget1)
        self.label_ny.setObjectName(_fromUtf8("label_ny"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_ny)
        self.lineEdit_ny = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_ny.setObjectName(_fromUtf8("lineEdit_ny"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_ny)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_width = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_width.setObjectName(_fromUtf8("lineEdit_width"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_width)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_height = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_height.setObjectName(_fromUtf8("lineEdit_height"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_height)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_extrapoints = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_extrapoints.setObjectName(_fromUtf8("lineEdit_extrapoints"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_extrapoints)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBox_scantype = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_scantype.setObjectName(_fromUtf8("comboBox_scantype"))
        self.comboBox_scantype.addItem(_fromUtf8(""))
        self.comboBox_scantype.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_scantype)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_linerate = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_linerate.setObjectName(_fromUtf8("lineEdit_linerate"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_linerate)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalScrollBar_shift = QtGui.QScrollBar(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar_shift.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar_shift.setSizePolicy(sizePolicy)
        self.horizontalScrollBar_shift.setMinimum(-100)
        self.horizontalScrollBar_shift.setMaximum(100)
        self.horizontalScrollBar_shift.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_shift.setObjectName(_fromUtf8("horizontalScrollBar_shift"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.horizontalScrollBar_shift)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_fastaxisrepeat = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_fastaxisrepeat.setObjectName(_fromUtf8("lineEdit_fastaxisrepeat"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_fastaxisrepeat)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setVerticalSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit_nstack = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_nstack.setObjectName(_fromUtf8("lineEdit_nstack"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_nstack)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_zstep = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_zstep.setObjectName(_fromUtf8("lineEdit_zstep"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_zstep)
        self.pushButton_settop = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_settop.setObjectName(_fromUtf8("pushButton_settop"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_settop)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.lineEdit_laser_power1 = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_laser_power1.sizePolicy().hasHeightForWidth())
        self.lineEdit_laser_power1.setSizePolicy(sizePolicy)
        self.lineEdit_laser_power1.setObjectName(_fromUtf8("lineEdit_laser_power1"))
        self.horizontalLayout_3.addWidget(self.lineEdit_laser_power1)
        self.lineEdit_laser_power2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_laser_power2.setObjectName(_fromUtf8("lineEdit_laser_power2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_laser_power2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_start = QtGui.QPushButton(self.layoutWidget1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/start_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon5)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtGui.QPushButton(self.layoutWidget1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/stop_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon6)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_shutter = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_shutter.setObjectName(_fromUtf8("pushButton_shutter"))
        self.horizontalLayout.addWidget(self.pushButton_shutter)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(GalvosForm)
        QtCore.QMetaObject.connectSlotsByName(GalvosForm)

    def retranslateUi(self, GalvosForm):
        GalvosForm.setWindowTitle(_translate("GalvosForm", "Form", None))
        self.pushButton_LaserOn.setText(_translate("GalvosForm", "Laser On", None))
        self.lineEdit_laser_output.setText(_translate("GalvosForm", "803", None))
        self.pushButton_CARS_switch.setText(_translate("GalvosForm", "CARS switch", None))
        self.pushButton_Shutter_Main.setText(_translate("GalvosForm", "Shutter Main", None))
        self.pushButton_LaserOff.setText(_translate("GalvosForm", "Laser Off", None))
        self.pushButton_APT_Motor.setText(_translate("GalvosForm", "Move APT Motor", None))
        self.pushButton_firstcut.setText(_translate("GalvosForm", "Vibratome Firstcut", None))
        self.label_13.setText(_translate("GalvosForm", "Mosaic Motors", None))
        self.lineEdit_Zaber_step.setText(_translate("GalvosForm", "1", None))
        self.label_14.setText(_translate("GalvosForm", "XY (cm)", None))
        self.pushButton_init.setText(_translate("GalvosForm", "init", None))
        self.pushButton_Settopleft.setText(_translate("GalvosForm", "Set Mosaic TL", None))
        self.pushButton_Setbottomright.setText(_translate("GalvosForm", "Set Mosaic BR", None))
        self.pushButton_mozaic.setText(_translate("GalvosForm", "Start mozaic", None))
        self.lineEdit_APT_Motors.setText(_translate("GalvosForm", "0", None))
        self.pushButton_getPosthorlabs.setText(_translate("GalvosForm", "Get focus position (Thorlabs motor)", None))
        self.label_15.setText(_translate("GalvosForm", "Moving APT Motor abs pos (mm) :", None))
        self.label_16.setText(_translate("GalvosForm", "Laser output (nm) : ", None))
        self.label_12.setText(_translate("GalvosForm", "Laser controls", None))
        self.pushButton_Shutter_1040.setText(_translate("GalvosForm", "Shutter 1040", None))
        self.pushButton_read_power.setText(_translate("GalvosForm", "Read Power", None))
        self.pushButton_move_laser_motor.setText(_translate("GalvosForm", "Move_fine_tune_laser_motor", None))
        self.label_11.setText(_translate("GalvosForm", "Z (um)", None))
        self.lineEdit_z_motor_step.setText(_translate("GalvosForm", "50", None))
        self.label_nx.setText(_translate("GalvosForm", "Nx", None))
        self.lineEdit_nx.setText(_translate("GalvosForm", "1000", None))
        self.label_ny.setText(_translate("GalvosForm", "Ny", None))
        self.lineEdit_ny.setText(_translate("GalvosForm", "1000", None))
        self.label_3.setText(_translate("GalvosForm", "Width (um)", None))
        self.lineEdit_width.setText(_translate("GalvosForm", "300", None))
        self.label_4.setText(_translate("GalvosForm", "Height (um)", None))
        self.lineEdit_height.setText(_translate("GalvosForm", "300", None))
        self.label_6.setText(_translate("GalvosForm", "Extra Points", None))
        self.lineEdit_extrapoints.setText(_translate("GalvosForm", "100", None))
        self.label_5.setText(_translate("GalvosForm", "Scan Type", None))
        self.comboBox_scantype.setItemText(0, _translate("GalvosForm", "SawTooth", None))
        self.comboBox_scantype.setItemText(1, _translate("GalvosForm", "Triangular", None))
        self.label_8.setText(_translate("GalvosForm", "Line Rate (Hz)", None))
        self.lineEdit_linerate.setText(_translate("GalvosForm", "150", None))
        self.label_7.setText(_translate("GalvosForm", "Shift", None))
        self.label_9.setText(_translate("GalvosForm", "Fast axis repeat", None))
        self.lineEdit_fastaxisrepeat.setText(_translate("GalvosForm", "1", None))
        self.label.setText(_translate("GalvosForm", "N stack", None))
        self.lineEdit_nstack.setText(_translate("GalvosForm", "8", None))
        self.label_2.setText(_translate("GalvosForm", "Z step (um)", None))
        self.lineEdit_zstep.setText(_translate("GalvosForm", "50", None))
        self.pushButton_settop.setText(_translate("GalvosForm", "Set Top", None))
        self.label_10.setText(_translate("GalvosForm", "Laser Power", None))
        self.lineEdit_laser_power1.setText(_translate("GalvosForm", "0", None))
        self.lineEdit_laser_power2.setText(_translate("GalvosForm", "0", None))
        self.pushButton_start.setText(_translate("GalvosForm", "Start", None))
        self.pushButton_stop.setText(_translate("GalvosForm", "Stop", None))
        self.pushButton_shutter.setText(_translate("GalvosForm", "Shutter", None))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GalvosForm = QtGui.QWidget()
    ui = Ui_GalvosForm()
    ui.setupUi(GalvosForm)
    GalvosForm.show()
    sys.exit(app.exec_())

